### ISSUE TITLE
Not a valid .NET Core host with .net 8 self hosted but works locally without problem

### ISSUE THREAD

**Issue by yoganr** [mono/t4#187]
Mono.TextTemplating.TemplatingEngineException: Not a valid .NET Core host
   at Mono.TextTemplating.TemplatingEngine.GetOrCreateCompiler() in /_/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs:line 67
   at Mono.TextTemplating.TemplatingEngine.CompileCode(IEnumerable`1 references, TemplateSettings settings, CodeCompileUnit ccu, CancellationToken token) in /_/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs:line 303
   at Mono.TextTemplating.TemplatingEngine.CompileTemplateInternal(ParsedTemplate pt, String content, ITextTemplatingEngineHost host, TemplateSettings settings, CancellationToken token) in /_/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs:line 277
   at Mono.TextTemplating.TemplatingEngine.CompileTemplateAsync(String content, ITextTemplatingEngineHost host, CancellationToken token) in /_/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs:line 207
   at Mono.TextTemplating.TemplatingEngine.ProcessTemplateAsync(String content, ITextTemplatingEngineHost host, CancellationToken token) in /_/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs:line 82
   at Mono.TextTemplating.TemplateGenerator.ProcessTemplateAsync(String inputFileName, String inputContent, String outputFileName, CancellationToken token) in /_/Mono.TextTemplating/Mono.TextTemplating/TemplateGenerator.cs:line 172
   at DocumentTemplateService.Globals.Implementations.T4TemplateService.T4TemplateService.ProcessTemplate(String template, Dictionary`2 parameters) in D:\build\utv-appsrv02\agent_2022\_work\62\s\DocumentTemplateService.Globals.Implementations\Services\T4TemplateService\T4TemplateService.cs:line 36
   at DocumentTemplateService.Data.Query.Services.DocumentTemplateQueryService.ProcessTemplate(DocumentTemplateDto template, String[] urls, String data, HttpRequest message) in D:\build\utv-appsrv02\agent_2022\_work\62\s\DocumentTemplateService.Data\Query\Services\DocumentTemplateQueryService.cs:line 120
   at DocumentTemplateService.Data.Query.Services.DocumentTemplateQueryService.Process(String templateName, String[] urls, String data, HttpRequest message) in D:\build\utv-appsrv02\agent_2022\_work\62\s\DocumentTemplateService.Data\Query\Services\DocumentTemplateQueryService.cs:line 76
   at DocumentTemplateService.Controller.DocumentTemplateController.Get(String keyOrTemplateName, ServiceQuery serviceQuery) in D:\build\utv-appsrv02\agent_2022\_work\62\s\DocumentTemplateService.Api\Controllers\DocumentTemplateController.cs:line 48
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at DocumentTemplateService.Api.Middleware.GlobalExceptionMiddleware.InvokeAsync(HttpContext httpContext)

**Comment by UweLesta** [comment]
FYI
This error occurs if
you use a package version below 2.3.1
and
your application is published in 'Deployment Mode' = 'Self-contained' (Not 'Framework-dependent')
and
there is no SDK on the server installed.

Mainly, you have to rethink your application if it is really necessary that your t4 template has to be compiled at runtime.

If so, use an appropriate version of Mono.Texttemplating that supports the environment variable DOTNET_ROOT which should point to the installed SDK on the server.
