### ISSUE TITLE
ArgumentNullException Thrown on Build

### ISSUE THREAD

**Issue by AceCoderLaura** [mono/t4#41]
I'm trying to make my Visual Studio T4 templates compatible with Visual Studio for Mac by installing and running the t4 command line tool in the build process but I get this error:

```
TransformAlliOS:
    dotnet tool install -g dotnet-t4
    Tool 'dotnet-t4' is already installed.
    The command "dotnet tool install -g dotnet-t4" exited with code 1.
    t4 /Users/adaptmac/Documents/AdaptSource/src/xivic/adapt.presentation.xamarinforms/adapt.presentation.xivic.ios/Assets.xcassets/attachment.imageset/Contents.tt
    Processing '/Users/adaptmac/Documents/AdaptSource/src/xivic/adapt.presentation.xamarinforms/adapt.presentation.xivic.ios/Assets.xcassets/attachment.imageset/Contents.tt' failed.
EXEC : error : Error running transform: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null. [/Users/adaptmac/Documents/AdaptSource/src/xivic/adapt.presentation.xamarinforms/adapt.presentation.xivic.ios/adapt.presentation.xivic.ios.csproj] [/Users/adaptmac/Documents/AdaptSource/src/xivic/adapt.presentation.xamarinforms/adapt.presentation.xivic.ios/adapt.presentation.xivic.ios.csproj]
    Parameter name: path1
       at System.IO.Path.Combine(String path1, String path2)
       at Mono.TextTemplating.TemplateGenerator.ResolvePath(String path) in C:\projects\t4\Mono.TextTemplating\Mono.TextTemplating\TemplateGenerator.cs:line 240
       at Mono.TextTemplating.TemplateGenerator.Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost.ResolvePath(String path) in C:\projects\t4\Mono.TextTemplating\Mono.TextTemplating\TemplateGenerator.cs:line 380
       at Microsoft.VisualStudio.TextTemplating.GeneratedTextTransformation8c16d7c.TransformText()
       --- End of inner exception stack trace ---
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Mono.TextTemplating.CompiledTemplate.Process() in C:\projects\t4\Mono.TextTemplating\Mono.TextTemplating\CompiledTemplate.cs:line 119
/Users/adaptmac/Documents/AdaptSource/src/xivic/adapt.presentation.xamarinforms/adapt.presentation.xivic.ios/iOS.Images.targets(71,9): error MSB3073: The command "t4 /Users/adaptmac/Documents/AdaptSource/src/xivic/adapt.presentation.xamarinforms/adapt.presentation.xivic.ios/Assets.xcassets/attachment.imageset/Contents.tt" exited with code 1. [/Users/adaptmac/Documents/AdaptSource/src/xivic/adapt.presentation.xamarinforms/adapt.presentation.xivic.ios/adapt.presentation.xivic.ios.csproj] [/Users/adaptmac/Documents/AdaptSource/src/xivic/adapt.presentation.xamarinforms/adapt.presentation.xivic.ios/adapt.presentation.xivic.ios.csproj]
  Done Building Project "/Users/adaptmac/Documents/AdaptSource/src/xivic/adapt.presentation.xamarinforms/adapt.presentation.xivic.ios/adapt.presentation.xivic.ios.csproj" (TransformAlliOS target(s)) -- FAILED.
```

These templates are only here because we don't have time to scale and write a manifest for every image in our Xamarin.iOS application.

You'll notice that the t4 command line tool is invoked in an Exec task calling msbuild.exe instead of using the MSBuild task. This is because the templates (along with generated, re-scaled images) are copied to each image folder and then included with a wildcard that needs to be re-evaluated. This re-evaluation is optimised away when using the MSBuild task.

I've included a binary log for further information that may help:
[msbuild-binary-log.zip](https://github.com/mono/t4/files/2887354/msbuild-binary-log.zip)

**Comment by mhutch** [comment]
It looks like your template code is calling ResolvePath with a null value?

**Comment by AceCoderLaura** [comment]
It's calling `Host.ResolvePath(string.Empty)`.

**Comment by mhutch** [comment]
Ah. What return value do you expect to get? `string.Empty`?

**Comment by AceCoderLaura** [comment]
In the Visual Studio T4 processor it returns the directory containing the template.
