### ISSUE TITLE
PlatformNotSupportedException with dotnet-t4-project-tool

### ISSUE THREAD

**Issue by ericsink** [mono/t4#42]
I have the global tool installed:

    T4 text template processor version 2.0.2+gbf09da0ad0

Using it, this command works:

    t4 -o tmp.cs -p:NAME=tmp -p:CONV=Cdecl -p:KIND=dynamic provider.tt

And I have a project dir with this in the csproj:

    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>netcoreapp2.1</TargetFramework>
      </PropertyGroup>
      <ItemGroup>
        <DotNetCliToolReference Include="dotnet-t4-project-tool" Version="2.0.3" />
      </ItemGroup>
    </Project>

And after a dotnet restore to install the local tool, dotnet t4 yields:

     T4 text template processor version 2.0.3+gd133b088d6

But if I run the same command as above, except with "dotnet " prepended, I get:

    System.PlatformNotSupportedException: Operation is not supported on this platform.
       at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
       at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromDomBatch(CompilerParameters options, CodeCompileUnit[] ea)
       at Mono.TextTemplating.TemplatingEngine.CompileCode(IEnumerable`1 references, TemplateSettings settings, CodeCompileUnit ccu)
       at Mono.TextTemplating.TemplatingEngine.CompileTemplateInternal(ParsedTemplate pt, String content, ITextTemplatingEngineHost host)
       at Mono.TextTemplating.TemplatingEngine.CompileTemplate(ParsedTemplate pt, String content, ITextTemplatingEngineHost host)
       at Mono.TextTemplating.ToolTemplateGenerator.ProcessTemplate(ParsedTemplate pt, String inputFile, String inputContent, String& outputFile)
       at Mono.TextTemplating.TextTransform.MainInternal(String[] args)
       at Mono.TextTemplating.TextTransform.Main(String[] args)

dotnet --version says 2.1.500

The problem seems reproducible on Windows and Mac.

**Comment by mhutch** [comment]
Looks like it's using the `net35` version of the engine assembly instead of the `netstandard2.0` version? Not sure how that's happening.

**Comment by borrrden** [comment]
This also happens simply by running `t4 -o <output> <input>`
